### ISSUE TITLE
代码逻辑错误

### ISSUE THREAD

**Issue by BlinkVoid** [zsdlove/ApkVulCheck#4]
##flag逻辑判断错误，所以app均被判断为未加固。需更改else中的条件为pass
并将flag初始为 false
def packerDetector(apkpath):
    packerType=""
    packersign=""
    flag=False
    zipfiles=zipfile.ZipFile(apkpath)
    nameList=zipfiles.namelist()
 for fileName in nameList:
        for packer in packer_features.keys():
            if packer in fileName:
                flag=True
                packerType=packer_features[packer]
                packersign=packer
                break
            else:
                pass

**Comment by BlinkVoid** [comment]
ApkVulCheck/plugin/shellDetector.py

**Comment by zsdlove** [comment]
Don't you see the break stmt inside the if stmt?There is no logical error in my code.
